### ISSUE TITLE
Interpreter crash when evaluating a native! redefined inside an object!

### ISSUE THREAD

**Issue by x8x** [red/red#1116]
This construct crash the interpreter:

``` rebol
o: object [
    sin*: :sin
    set 'sin does [
        sin* none
    ]
]
```

Result from console:

``` rebol
red>> o: object [
[     sin*: :sin
[     set 'sin does [
[      sin* none
[     ]
[    ]
== make object! [
    sin*: routine ["Returns the trigonometric sine"...
red>> sin

*** Runtime Error 1: access violation
*** at: 0002752Dh

```

**Comment by dockimbel** [comment]
Fixed by commit [852be588](https://github.com/red/red/commit/e42ff022b11de571fbe2ee2de9fb2861852be588).

**Comment by x8x** [comment]
```rebol
  o: object [
[        sin*: :sin
[        set 'sin does [
[            sin* none
[        ]
[    ]
;   make object! [
    sin*: routine ["Returns the trigonometric sine"...
  sin
*** Script error: sin* does not allow none for its <anon> argument

  o/sin*
*** Script error: sin* is missing its angle argument
*** Where: sin*
```

`<anon> argument` should be `angle argument`

**Comment by dockimbel** [comment]
The `<anon>` issue has been fixed now.

**Comment by x8x** [comment]
not sure it's fixed, here an example with latest nightly:
```rebol
red>> o: object [
[        sin*: :sin
[        set 'sin does [
[            sin* none
[        ]
[    ]
== make object! [
    sin*: routine ["Returns the trigonometric sine"...
red>> sin
*** Script error: sin* does not allow none for its <anon> argument
*** Where: sin*
```

**Comment by x8x** [comment]
Should this one be reopened? I still get `<anon>` instead of `angle`:
```
  o: object [
[           sin*: :sin
[            set 'sin does [
[                sin* none
[            ]
[        ]
;   make object! [
    sin*: routine [
        "Returns the trigonomet...
  sin
*** Script Error: sin* does not allow none! for its <anon> argument
*** Where: sin*
```

**Comment by dockimbel** [comment]
This code now works properly in the interpreter.
